import type { BookingTemplateProps, TemplateProps } from "../types";
import { action, asset, localized, records, section, supportAsset } from "../content";
import "./bloom.css";

export function BloomSite({ snapshot, locale, applicationName, publicRoot, rootStyle }: TemplateProps) {
  const hero = section(snapshot.sections, "hero"); const services = section(snapshot.sections, "services");
  const benefits = section(snapshot.sections, "benefits"); const providers = section(snapshot.sections, "providers");
  const process = section(snapshot.sections, "process"); const testimonials = section(snapshot.sections, "testimonials");
  const faq = section(snapshot.sections, "faq"); const locations = section(snapshot.sections, "locations");
  const booking = section(snapshot.sections, "booking_cta"); const primary = action(hero.primaryAction, locale);
  const heroAsset = asset(snapshot.compiledDesign, "hero.primary");
  return <div data-pe-root data-pe-recipe={snapshot.recipeKey} className="bloom-site" data-template="bloom-hair-v1" style={rootStyle}>
    <header className="bloom-nav"><a href={publicRoot}>{applicationName}</a><nav><a href="#services">Services</a><a href="#people">Our people</a><a href="#studio">The studio</a></nav>{primary ? <a className="bloom-button" href={primary.href}>Book an appointment</a> : null}<small>Good people<br />great hair</small></header>
    <main>
      <section className="bloom-hero"><div><p className="bloom-label">Hair care for brighter days</p><h1>{localized(hero.title, locale)}</h1><p>{localized(hero.subtitle || hero.body, locale)}</p>{primary ? <a className="bloom-button" href={primary.href}>{primary.label} →</a> : null}<small>People&nbsp;&nbsp;—&nbsp;&nbsp;Hair&nbsp;&nbsp;—&nbsp;&nbsp;A brighter you</small></div><figure>{heroAsset ? <img src={heroAsset.src} alt={heroAsset.alt} /> : null}<figcaption>Come<br />as you<br />are</figcaption></figure></section>
      <form className="bloom-find" action={primary?.href}><strong>Book an appointment<small>Find your moment.</small></strong><label>Service<select aria-label="Service"><option>Cut &amp; style</option></select></label><label>Stylist<select aria-label="Stylist"><option>Anyone lovely</option></select></label><label>Date<input aria-label="Date" placeholder="Choose a date" /></label><button>Find a time →</button></form>
      <section className="bloom-services" id="services"><div className="bloom-section-title"><p className="bloom-label">Our services</p><h2>{localized(services.title, locale)}</h2><small>Expert care.<br />A warmer you.</small></div><div className="bloom-service-grid">{records(services.items).map((item,index)=><article key={index}><div><b>0{index+1}</b><h3>{localized(item.name,locale)}</h3><span>From ETB {String(item.price||"")}</span><p>{localized(item.summary,locale)}</p></div><img src={supportAsset("bloom",(index%3)+1)} alt="" /></article>)}</div></section>
      <section className="bloom-care"><p className="bloom-label">Why {applicationName}</p><h2>{localized(benefits.title,locale)}</h2><div>{records(benefits.items).map((item,index)=><article key={index}><b>{["≋","♡","♢"][index%3]}</b><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></article>)}</div></section>
      <section className="bloom-people" id="people"><div><p className="bloom-label">Our people</p><h2>Good people.<br />Great hands.</h2><p>{localized(providers.intro,locale)}</p></div><div>{records(providers.items).map((item,index)=><article key={index}><img src={supportAsset("bloom",index===0?1:2)} alt=""/><h3>{localized(item.name,locale)}</h3><p>{localized(item.role,locale)}</p></article>)}</div></section>
      <section className="bloom-process"><img src={supportAsset("bloom",3)} alt="The Bole salon"/><div><div className="bloom-process-head"><div><p className="bloom-label">The {applicationName} experience</p><h2>{localized(process.title,locale)}</h2></div><p>{localized(process.intro,locale)}</p></div>{records(process.items).map((item,index)=><article key={index}><b>0{index+1}</b><div><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></div></article>)}</div></section>
      <section className="bloom-testimonials"><div><p className="bloom-label">Kind words</p>{records(testimonials.items).slice(0,1).map((item,index)=><blockquote key={index}>“{localized(item.quote,locale)}”<cite>— {localized(item.attribution,locale)}</cite></blockquote>)}</div><div>{records(testimonials.items).slice(1).map((item,index)=><blockquote key={index}>“{localized(item.quote,locale)}”<cite>— {localized(item.attribution,locale)}</cite></blockquote>)}</div></section>
      <section className="bloom-faq"><div><p className="bloom-label">Frequently asked questions</p><h2>You ask,<br/>we answer.</h2></div><div>{records(faq.items).map((item,index)=><details key={index}><summary>{localized(item.question,locale)}</summary><p>{localized(item.answer,locale)}</p></details>)}</div></section>
      <section className="bloom-studio" id="studio"><img src={supportAsset("bloom",3)} alt="The studio interior"/><div><p className="bloom-label">Visit our studio</p><h2>{localized(locations.title,locale)}</h2>{records(locations.items).slice(0,1).map((item,index)=><address key={index}>{localized(item.address,locale)}<br/>{localized(item.hours,locale)}<br/>{String(item.phone||"")}</address>)}</div><img src={supportAsset("bloom",2)} alt="Natural hair detail"/></section>
      <section className="bloom-final"><div><p className="bloom-label">Ready for your next feel-good moment?</p><h2>{localized(booking.title,locale)}</h2></div>{action(booking.action,locale)?<a href={action(booking.action,locale)?.href}>{action(booking.action,locale)?.label} →</a>:null}</section>
    </main><footer className="bloom-footer"><a href={publicRoot}>{applicationName}</a><nav>Services&nbsp;&nbsp;&nbsp; Our people&nbsp;&nbsp;&nbsp; The studio</nav><small>© {new Date().getFullYear()} {applicationName}</small></footer>
  </div>;
}

export function BloomBooking({ snapshot,locale,applicationName,publicRoot,rootStyle,bookingPath }:BookingTemplateProps){const hero=section(snapshot.sections,"hero");return <main data-pe-booking data-pe-recipe={snapshot.recipeKey} className="bloom-site bloom-booking" style={rootStyle}><header className="bloom-nav"><a href={publicRoot}>{applicationName}</a><a href={publicRoot}>Back to the studio</a></header><section><div><p className="bloom-label">Your next feel-good moment</p><h1>{localized(hero.title,locale)}</h1><p>{localized(hero.subtitle,locale)}</p>{bookingPath?<a className="bloom-button" href={bookingPath}>Choose a service →</a>:null}</div><img src={supportAsset("bloom",1)} alt="Natural hair appointment"/></section></main>}
