import type { BookingTemplateProps, TemplateProps } from "../types";
import { action, asset, brandLogo, localAsset, localized, records, section, supportAsset } from "../content";
import "./meron.css";

export function MeronSite({snapshot,locale,applicationName,publicRoot,rootStyle,mode,toggleMode}:TemplateProps){
 const hero=section(snapshot.sections,"hero"),services=section(snapshot.sections,"services"),benefits=section(snapshot.sections,"benefits"),providers=section(snapshot.sections,"providers"),process=section(snapshot.sections,"process"),testimonials=section(snapshot.sections,"testimonials"),faq=section(snapshot.sections,"faq"),locations=section(snapshot.sections,"locations"),booking=section(snapshot.sections,"booking_cta");
 const primary=action(hero.primaryAction,locale),heroAsset=asset(snapshot.compiledDesign,"hero.primary");
 return <div data-pe-root data-pe-recipe={snapshot.recipeKey} data-pe-mode={mode} className="meron-site" data-template="meron-atelier-v1" style={rootStyle}><header className="meron-nav"><a href={publicRoot}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : null}{applicationName.toUpperCase()}</a><nav><a href={`${publicRoot}/blog`}>Journal</a><a href={`${publicRoot}/gallery`}>Gallery</a><a href="#craft">Our craft</a><a href="#services">Services</a><a href="#story">Journal</a></nav><small>Tailoring a more deliberate life</small><button type="button" className="meron-mode" onClick={toggleMode} aria-label={`Switch to ${mode === "dark" ? "light" : "dark"} mode`}><span>{mode === "dark" ? "LIGHT" : "DARK"}</span><i aria-hidden="true"></i></button>{primary?<a className="meron-button" href={primary.href}>Book a fitting ↗</a>:null}</header><main>
 <section className="meron-hero"><div><p className="meron-label">Bespoke tailoring · by appointment</p><h1>{localized(hero.title,locale)}</h1><p>{localized(hero.subtitle||hero.body,locale)}</p>{primary?<a className="meron-button" href={primary.href}>{primary.label} ↗</a>:null}<small>Good clothes change<br/>how you move through<br/>the world.</small></div><figure>{heroAsset?<img src={heroAsset.src} alt={heroAsset.alt}/>:null}<img src={supportAsset("meron",2)} alt="Precise hand stitching"/><figcaption>A finer kind<br/>of tomorrow</figcaption></figure></section>
 <section className="meron-services" id="services"><div><h2>A wardrobe,<br/>considered.</h2><i></i><p>{localized(services.intro,locale)}</p></div>{records(services.items).map((item,index)=><article key={index}><b>0{index+1}</b><h3>{localized(item.name,locale)}</h3><p>{localized(item.summary,locale)}</p><img src={supportAsset("meron",(index%2)+1)} alt=""/></article>)}</section>
 <section className="meron-details" id="craft"><div><h2>The difference<br/>is in the details.</h2><i></i><p>Exceptional materials.<br/>Considered techniques.<br/>A longer lasting wardrobe.</p></div><img src={supportAsset("meron",2)} alt="Hand stitching on fine cloth"/><div>{records(benefits.items).map((item,index)=><article key={index}><b>0{index+1}</b><div><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></div></article>)}</div></section>
 <section className="meron-founder" id="story"><img src={localAsset(records(providers.items)[0]?.image,supportAsset("meron",1))} alt={localized(records(providers.items)[0]?.name,locale)}/><div><p className="meron-label">Our founder</p><h2>{localized(providers.title,locale)}</h2><i></i>{records(providers.items).slice(0,1).map((item,index)=><article key={index}><h3>{localized(item.name,locale)} — {localized(item.role,locale)}</h3><p>{localized(item.bio,locale)||localized(providers.intro,locale)}</p></article>)}{primary?<a className="meron-button" href={primary.href}>Our approach ↗</a>:null}</div><blockquote>“Good tailoring is a conversation — between you, the cloth, and a more intentional tomorrow.”</blockquote></section>
 <section className="meron-process"><div><h2>{localized(process.title,locale)}</h2><i></i><p>A considered process.<br/>A lasting result.</p></div>{records(process.items).map((item,index)=><article key={index}><b>0{index+1}</b><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></article>)}</section>
 <section className="meron-story"><img src={supportAsset("meron",3)} alt="A considered atelier"/><div><p className="meron-label">Client story</p>{records(testimonials.items).slice(0,1).map((item,index)=><blockquote key={index}>“{localized(item.quote,locale)}”<cite>{localized(item.attribution,locale)}</cite></blockquote>)}</div></section>
 <section className="meron-faq"><div><h2>Before your<br/>first fitting.</h2><i></i><p>Simple answers,<br/>for a smoother experience.</p></div><div>{records(faq.items).map((item,index)=><details key={index}><summary>{localized(item.question,locale)}<span>+</span></summary><p>{localized(item.answer,locale)}</p></details>)}</div></section>
 <section className="meron-location"><img src={supportAsset("meron",3)} alt="The Kazanchis atelier"/><div><p className="meron-label">Our studio</p><h2>{localized(locations.title,locale)}</h2><i></i>{records(locations.items).slice(0,1).map((item,index)=><address key={index}>{localized(item.address,locale)}<br/>{localized(item.hours,locale)}<br/>{String(item.phone||"")}</address>)}{action(booking.action,locale)?<a className="meron-button" href={action(booking.action,locale)?.href}>{action(booking.action,locale)?.label} ↗</a>:null}</div><small>A quieter<br/>kind of<br/>progress</small></section>
 </main><footer className="meron-footer"><a href={publicRoot}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : null}{applicationName.toUpperCase()}</a><nav>Our craft&nbsp;&nbsp;&nbsp; Services&nbsp;&nbsp;&nbsp; Journal&nbsp;&nbsp;&nbsp; Contact</nav><small>Made for a more deliberate life.</small></footer></div>}

export function MeronBooking({snapshot,locale,applicationName,publicRoot,rootStyle,bookingPath,mode,toggleMode}:BookingTemplateProps){const hero=section(snapshot.sections,"hero");return <main data-pe-booking data-pe-recipe={snapshot.recipeKey} data-pe-mode={mode} className="meron-site meron-booking" style={rootStyle}><header className="meron-nav"><a href={publicRoot}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : null}{applicationName.toUpperCase()}</a><button type="button" className="meron-mode" onClick={toggleMode} aria-label={`Switch to ${mode === "dark" ? "light" : "dark"} mode`}><span>{mode === "dark" ? "LIGHT" : "DARK"}</span><i aria-hidden="true"></i></button><a href={publicRoot}>Back to atelier</a></header><section><div><p className="meron-label">Arrange your fitting</p><h1>{localized(hero.title,locale)}</h1><p>{localized(hero.subtitle,locale)}</p>{bookingPath?<a className="meron-button" href={bookingPath}>Continue to appointments ↗</a>:null}</div><img src={supportAsset("meron",2)} alt="Tailoring details"/></section></main>}
