import type { BookingTemplateProps, TemplateProps } from "../types";
import { action, asset, brandLogo, localAsset, localized, records, section, supportAsset } from "../content";
import "./abugida.css";
import { AbugidaNewsletter } from "./AbugidaNewsletter";

export function AbugidaSite({snapshot,locale,applicationName,publicRoot,rootStyle,mode,toggleMode}:TemplateProps){
 const hero=section(snapshot.sections,"hero"),services=section(snapshot.sections,"services"),benefits=section(snapshot.sections,"benefits"),providers=section(snapshot.sections,"providers"),process=section(snapshot.sections,"process"),testimonials=section(snapshot.sections,"testimonials"),faq=section(snapshot.sections,"faq"),locations=section(snapshot.sections,"locations"),booking=section(snapshot.sections,"booking_cta"); const primary=action(hero.primaryAction,locale),heroAsset=asset(snapshot.compiledDesign,"hero.primary");
 return <div data-pe-root data-pe-recipe={snapshot.recipeKey} data-pe-mode={mode} className="abugida-site" data-template="abugida-language-v1" style={rootStyle}><header className="abugida-nav"><a href={publicRoot} aria-label={applicationName}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : <b>አ</b>}<span>{applicationName}</span></a><nav><a href={`${publicRoot}/blog`}>Journal</a><a href={`${publicRoot}/gallery`}>Gallery</a><a href="#practice">Practice</a><a href="#method">How it works</a><a href="#rooms">Our rooms</a></nav><button type="button" className="abugida-mode" onClick={toggleMode} aria-label={`Switch to ${mode === "dark" ? "light" : "dark"} mode`}><span aria-hidden="true">{mode === "dark" ? "☀" : "◐"}</span>{mode === "dark" ? "LIGHT" : "DARK"}</button>{primary?<a href={primary.href}>Start a conversation ↗</a>:null}</header><main>
 <section className="abugida-hero"><div className="abugida-number">01</div><div><p className="abugida-label">Speak · listen · belong</p><h1>{localized(hero.title,locale)}</h1><p>{localized(hero.subtitle||hero.body,locale)}</p>{primary?<a className="abugida-button" href={primary.href}>{primary.label} ↗</a>:null}</div><figure>{heroAsset?<img src={heroAsset.src} alt={heroAsset.alt}/>:null}<figcaption>Useful language.<br/>Real situations.</figcaption></figure></section>
 <section className="abugida-marquee"><span>WORK</span><i>●</i><span>STUDY</span><i>●</i><span>EVERYDAY LIFE</span><i>●</i><span>ONE CONVERSATION AT A TIME</span></section>
 <section className="abugida-practice" id="practice"><header><p className="abugida-label">Choose your practice</p><h2>{localized(services.title,locale)}</h2><p>{localized(services.intro,locale)}</p></header><div>{records(services.items).map((item,index)=><article key={index}><span>0{index+1}</span><h3>{localized(item.name,locale)}</h3><p>{localized(item.summary,locale)}</p><footer><b>{String(item.durationMinutes||"")} min</b><b>ETB {String(item.price||"")}</b></footer></article>)}</div></section>
 <section className="abugida-method" id="method"><figure><img src={supportAsset("abugida",2)} alt="Language practice materials"/><figcaption>Words become useful when they belong to your life.</figcaption></figure><div><p className="abugida-label">Practice, not performance</p><h2>{localized(benefits.title,locale)}</h2>{records(benefits.items).map((item,index)=><article key={index}><b>{index+1}</b><div><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></div></article>)}</div></section>
 <section className="abugida-coaches"><div><p className="abugida-label">People to practise with</p><h2>{localized(providers.title,locale)}</h2></div><div>{records(providers.items).map((item,index)=><article key={index}><img src={localAsset(item.image,supportAsset("abugida",1))} alt={localized(item.name,locale)}/><span><b>{localized(item.name,locale)}</b>{localized(item.role,locale)}</span></article>)}</div></section>
 <section className="abugida-process"><p className="abugida-label">A repeatable rhythm</p><div>{records(process.items).map((item,index)=><article key={index}><b>0{index+1}</b><h3>{localized(item.title,locale)}</h3><p>{localized(item.description,locale)}</p></article>)}</div></section>
 <section className="abugida-quote">{records(testimonials.items).slice(0,1).map((item,index)=><blockquote key={index}>“{localized(item.quote,locale)}”<cite>{localized(item.attribution,locale)}</cite></blockquote>)}<img src={supportAsset("abugida",1)} alt="Conversation practice"/></section>
 <section className="abugida-questions"><div><p className="abugida-label">Questions are welcome</p><h2>Before we begin.</h2></div><div>{records(faq.items).map((item,index)=><details key={index}><summary>{localized(item.question,locale)}<span>↘</span></summary><p>{localized(item.answer,locale)}</p></details>)}</div></section>
 <section className="abugida-rooms" id="rooms"><img src={supportAsset("abugida",3)} alt="The Arat Kilo learning room"/><div><p className="abugida-label">Arat Kilo · Addis Ababa</p><h2>{localized(locations.title,locale)}</h2>{records(locations.items).slice(0,1).map((item,index)=><address key={index}>{localized(item.address,locale)}<br/>{localized(item.hours,locale)}<br/>{String(item.phone||"")}</address>)}{action(booking.action,locale)?<a className="abugida-button" href={action(booking.action,locale)?.href}>{action(booking.action,locale)?.label} ↗</a>:null}</div></section>
 <AbugidaNewsletter snapshot={snapshot} applicationName={applicationName} locale={locale} publicRoot={publicRoot} /></main><footer className="abugida-footer"><a href={publicRoot} aria-label={applicationName}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : <b>አ</b>} {applicationName}</a><p>Language for the moments that matter.</p><small>© {new Date().getFullYear()} {applicationName}</small></footer></div>}

export function AbugidaBooking({snapshot,locale,applicationName,publicRoot,rootStyle,bookingPath,mode,toggleMode}:BookingTemplateProps){const hero=section(snapshot.sections,"hero");return <main data-pe-booking data-pe-recipe={snapshot.recipeKey} data-pe-mode={mode} className="abugida-site abugida-booking" style={rootStyle}><header className="abugida-nav"><a href={publicRoot} aria-label={applicationName}>{brandLogo(snapshot.compiledDesign) ? <img className="pe-brand-logo" src={brandLogo(snapshot.compiledDesign)} alt="" /> : <b>አ</b>}<span>{applicationName}</span></a><button type="button" className="abugida-mode" onClick={toggleMode} aria-label={`Switch to ${mode === "dark" ? "light" : "dark"} mode`}><span aria-hidden="true">{mode === "dark" ? "☀" : "◐"}</span>{mode === "dark" ? "LIGHT" : "DARK"}</button><a href={publicRoot}>Back to the studio</a></header><section><div><p className="abugida-label">Put a conversation on the calendar</p><h1>{localized(hero.title,locale)}</h1><p>{localized(hero.subtitle,locale)}</p>{bookingPath?<a className="abugida-button" href={bookingPath}>Choose a practice time ↗</a>:null}</div><img src={supportAsset("abugida",1)} alt="Language practice"/></section></main>}
