import { test, expect } from "playwright/test";
import { articleHistory, businessIsolation } from "./owner-validation.mjs";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

let managedStaff;
test.afterEach(async () => { await managedStaff?.close(); managedStaff = undefined; });

test("website-owner-journey", async ({ page }, testInfo) => {
  page.setDefaultTimeout(20000);
  page.setDefaultNavigationTimeout(30000);
  const marker = process.env.WEBSITE_QA_MARKER;
  expect(marker).toMatch(/^WQA-[a-zA-Z0-9]+$/);
  const identity = await page.request.get("/api/method/frappe.auth.get_logged_user");
  expect((await identity.json()).message).toBe("content-browser-owner@example.test");
  await page.goto("/onboarding", { waitUntil: "networkidle" });
  await page.getByLabel("Business name", { exact: true }).fill(marker);
  await page.getByLabel("Location name", { exact: true }).fill(`${marker} Main`);
  await page.getByLabel("First service name", { exact: true }).fill(`${marker} Consultation`);
  await page.getByRole("button", { name: "Create business", exact: true }).click();
  await expect(page).toHaveURL(/\/home/);
  await page.goto("/settings/business", { waitUntil: "networkidle" });
  await page.locator('[data-qa="business-offering"]').filter({ hasText: marker }).getByRole("button", { name: "Publish booking page", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await page.goto("/settings/team", { waitUntil: "networkidle" });
  const invitations = page.getByRole("region", { name: "Staff invitations" });
  await invitations.getByLabel("Name", { exact: true }).fill("Workbook invited staff");
  await invitations.getByLabel("Email", { exact: true }).fill(`${marker.toLowerCase()}-staff@example.test`);
  await invitations.getByRole("button", { name: "Confirm local invitation", exact: true }).click();
  const invitationLink = invitations.getByRole("link", { name: "Open local invitation", exact: true });
  await expect(invitationLink).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("website-staff-invitation-inbox.png"), fullPage: true });
  const staffPassword = `Staff own password 2026! ${crypto.randomUUID()}`;
  const staffContext = await page.context().browser().newContext();
  try {
    const staffPage = await staffContext.newPage();
    await staffPage.goto(new URL(await invitationLink.getAttribute("href"), page.url()).href, { waitUntil: "networkidle" });
    await staffPage.getByLabel("New account password", { exact: true }).fill(staffPassword);
    await staffPage.getByRole("button", { name: "Accept invitation", exact: true }).click();
    await expect(staffPage.getByRole("status")).toContainText("Your account is ready");
    await staffPage.screenshot({ path: testInfo.outputPath("website-staff-invitation-accepted.png"), fullPage: true });
  } finally { await staffContext.close(); }
  await page.getByLabel("Account email", { exact: true }).fill(`${marker.toLowerCase()}-staff@example.test`);
  await page.getByRole("checkbox", { name: `${marker} Main`, exact: true }).check();
  await page.getByRole("button", { name: "Assign", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("assigned as Receptionist");
  const credentialFile = join(process.env.WEBSITE_QA_PRIVATE_DIRECTORY, "staff-credentials.json");
  writeFileSync(credentialFile, JSON.stringify({ username: `${marker.toLowerCase()}-staff@example.test`, password: staffPassword }), { mode: 0o600 });
  const rawProfile = execFileSync("/usr/local/bin/bench", ["--site", process.env.WEBSITE_QA_SITE, "execute", "appointment.tests.staff_browser_bridge.login", "--kwargs", JSON.stringify({ credential_file: credentialFile })], {
    cwd: process.env.FRAPPE_BENCH_ROOT, encoding: "utf8", timeout: 60000,
  });
  const profile = JSON.parse(rawProfile.trim().split("\n").at(-1));
  expect(profile.roles).toContain("Front Desk");
  expect(profile.roles).not.toContain("Organization Manager");
  managedStaff = await page.context().browser().newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL, storageState: profile.storage_state });
  const staffClock = new Date();
  staffClock.setUTCHours(9, 0, 0, 0);
  await managedStaff.clock.setFixedTime(staffClock);
  const receptionist = await managedStaff.newPage();
  const signedInStaff = await receptionist.request.get("/api/method/frappe.auth.get_logged_user");
  expect((await signedInStaff.json()).message).toBe(profile.user);
  await receptionist.goto("/reception", { waitUntil: "networkidle" });
  await expect(receptionist).toHaveURL(/\/reception/);
  await receptionist.screenshot({ path: testInfo.outputPath("website-receptionist-managed-session.png"), fullPage: true });
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await expect(page.getByRole("heading", { name: "Website setup", exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Business", exact: true }).selectOption({ label: marker });
  await page.getByRole("combobox", { name: "Business focus", exact: true }).selectOption("health");
  await page.getByRole("combobox", { name: "Feeling", exact: true }).selectOption("calm");
  await page.getByRole("combobox", { name: "Primary audience", exact: true }).selectOption("patients");
  await page.getByRole("combobox", { name: "Preferred content density", exact: true }).selectOption("comfortable");
  await page.getByRole("button", { name: "Preview selected template", exact: true }).click();
  await expect(page.getByRole("region", { name: "Website live preview" })).toBeVisible();
  await page.waitForLoadState("networkidle");
  await page.evaluate(() => scrollTo(0, 0));
  await page.mouse.move(0, 0);
  await page.evaluate(() => document.activeElement?.blur());
  await page.screenshot({ path: testInfo.outputPath("website-template-comparison-desktop.png"), fullPage: true, animations: "disabled" });
  await page.getByLabel("Website name", { exact: true }).fill(marker);
  await page.getByLabel("Website address", { exact: true }).fill(marker.toLowerCase());
  await page.getByRole("button", { name: "Create website draft", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeVisible();
  await page.getByLabel("Logo or favicon image", { exact: true }).setInputFiles(process.env.WEBSITE_QA_IMAGE);
  await page.getByLabel("I have permission to display this identity image publicly.", { exact: true }).check();
  await page.getByRole("button", { name: "Upload identity image", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("identity image is saved");
  await expect(page.getByAltText("logo primary preview", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Identity image type", exact: true }).selectOption("favicon");
  await page.getByLabel("Logo or favicon image", { exact: true }).setInputFiles(process.env.WEBSITE_QA_IMAGE);
  await page.getByLabel("I have permission to display this identity image publicly.", { exact: true }).check();
  await page.getByRole("button", { name: "Upload identity image", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("identity image is saved");
  await expect(page.getByAltText("favicon preview", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "content", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("saved");
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("button", { name: `Resume ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "Save and return later", exact: true }).click();
  await expect(page).toHaveURL(/\/home/);
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: `Resume ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "features", exact: true }).click();
  await page.getByLabel("blog", { exact: true }).check();
  await page.getByLabel("gallery", { exact: true }).check();
  await page.getByLabel("newsletter", { exact: true }).check();
  await page.getByRole("button", { name: "readiness", exact: true }).click();
  await page.getByRole("button", { name: "Check readiness", exact: true }).click();
  await expect(page.getByText("Ready: website draft", { exact: true })).toBeVisible();
  await expect(page.getByText("Ready: booking", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Live preview of saved draft", exact: true }).click();
  await expect(page.getByRole("region", { name: "Website live preview" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("website-preview-desktop.png"), fullPage: true });
  const preview = page.getByRole("region", { name: "Website live preview" });
  for (const surface of ["booking", "blog", "article", "gallery", "collection"]) {
    await preview.getByRole("combobox", { name: "Surface", exact: true }).selectOption(surface);
    await expect(preview.locator("[data-pe-recipe]")).toBeVisible();
    if (["article", "collection"].includes(surface)) await expect(preview).toContainText("Example");
    await preview.screenshot({ path: testInfo.outputPath(`website-private-preview-${surface}.png`) });
  }
  await preview.getByRole("button", { name: "Preview mobile", exact: true }).click();
  await preview.getByRole("button", { name: "Preview dark mode", exact: true }).click();
  await expect(preview.locator('[data-pe-mode="dark"]')).toBeVisible();
  await preview.screenshot({ path: testInfo.outputPath("website-private-preview-mobile-dark.png") });
  await preview.getByRole("combobox", { name: "Surface", exact: true }).selectOption("landing");
  await preview.getByRole("button", { name: "Preview desktop", exact: true }).click();
  await preview.getByRole("button", { name: "Preview light mode", exact: true }).click();
  await page.getByRole("button", { name: "Publish website", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await page.screenshot({ path: testInfo.outputPath("website-published-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath("website-published-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/settings/website/content", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Website", exact: true }).selectOption({ label: marker });
  await page.getByLabel("Article title", { exact: true }).fill(`${marker} Preparing for your visit`);
  await page.getByLabel("Article address", { exact: true }).fill("preparing-for-your-visit");
  await page.getByLabel("Summary", { exact: true }).fill("A guide to preparing for your consultation.");
  await page.getByLabel("Article text", { exact: true }).fill("# Preparing for your visit\nBring your questions and allow time to arrive.");
  await page.getByRole("button", { name: "Save article draft", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("draft saved");
  await page.getByRole("button", { name: "Publish article", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await expect(page.getByRole("region", { name: "Publication history", exact: true })).toContainText("/blog/preparing-for-your-visit");
  await page.screenshot({ path: testInfo.outputPath("website-article-workspace.png"), fullPage: true, mask: [page.locator("time")] });
  const galleryEditor = page.getByRole("region", { name: "Gallery editor" });
  await galleryEditor.getByLabel("Collection title", { exact: true }).fill("Around our clinic");
  await galleryEditor.getByLabel("Collection address", { exact: true }).fill("around-our-clinic");
  await galleryEditor.getByLabel("Gallery image", { exact: true }).setInputFiles(process.env.WEBSITE_QA_IMAGE);
  await galleryEditor.getByLabel("Image description", { exact: true }).fill("A consultation at the clinic");
  await galleryEditor.getByLabel("Caption", { exact: true }).fill("A welcoming place to talk about your health.");
  await galleryEditor.getByRole("checkbox").check();
  await galleryEditor.getByRole("button", { name: "Save gallery draft", exact: true }).click();
  await expect(galleryEditor.getByRole("status")).toContainText("draft saved");
  await galleryEditor.getByRole("button", { name: "Publish gallery", exact: true }).click();
  await expect(galleryEditor.getByRole("status")).toContainText("published");
  // Public reads use a separate guest context, without the owner login cookies.
  const guest = await page.context().browser().newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL });
  const publicPage = await guest.newPage();
  publicPage.setDefaultTimeout(20000);
  publicPage.setDefaultNavigationTimeout(30000);
  await publicPage.goto(`/${marker.toLowerCase()}`, { waitUntil: "networkidle" });
  await expect(publicPage.locator("h1")).toContainText(marker);
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-landing.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/book`, { waitUntil: "networkidle" });
  await expect(publicPage.locator("h1")).toContainText(marker);
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-book.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/blog`, { waitUntil: "networkidle" });
  await expect(publicPage.locator("main")).toContainText("Preparing for your visit");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-blog.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/blog/preparing-for-your-visit`, { waitUntil: "networkidle" });
  await expect(publicPage.locator("main")).toContainText("Bring your questions");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-article.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/gallery`, { waitUntil: "networkidle" });
  await expect(publicPage.locator("main")).toContainText("Around our clinic");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-gallery.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/gallery/around-our-clinic`, { waitUntil: "networkidle" });
  await expect(publicPage.getByRole("img", { name: "A consultation at the clinic", exact: true })).toBeVisible();
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-collection-desktop.png"), fullPage: true });
  await publicPage.setViewportSize({ width: 390, height: 844 });
  await publicPage.getByRole("button", { name: "Switch to dark mode", exact: true }).click();
  await expect(publicPage.locator('[data-pe-mode="dark"]')).toBeVisible();
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-collection-mobile-dark.png"), fullPage: true });
  await page.goto("/settings/website/newsletter", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Website", exact: true }).selectOption({ label: marker });
  await page.getByLabel("Sender email", { exact: true }).fill("sender@example.test");
  await page.getByLabel("Sender name", { exact: true }).fill("Clinic care team");
  await page.getByRole("button", { name: "Request sender verification", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("verification message");
  await page.getByRole("button", { name: "Open Sender Verification for sender@example.test", exact: true }).click();
  const senderPath = await page.getByRole("link", { name: "Open newsletter action", exact: true }).getAttribute("href");
  await publicPage.goto(senderPath, { waitUntil: "networkidle" });
  await publicPage.getByRole("button", { name: "Verify newsletter sender", exact: true }).click();
  await expect(publicPage.getByRole("status")).toContainText("External delivery remains disabled");
  await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Campaign sender", exact: true })).toContainText("Verified Local");
  await publicPage.goto(`/${marker.toLowerCase()}/blog`, { waitUntil: "networkidle" });
  const signup = publicPage.locator('[data-newsletter-template="tena"]');
  await signup.getByLabel("Email address", { exact: true }).fill("reader@example.test");
  await expect(signup.getByRole("button", { name: "Receive care updates", exact: true })).toBeDisabled();
  await signup.getByRole("checkbox").check();
  await signup.getByRole("button", { name: "Receive care updates", exact: true }).click();
  await expect(signup.getByRole("status")).toContainText("Confirmation is captured");
  await publicPage.screenshot({ path: testInfo.outputPath("website-newsletter-signup-mobile-dark.png"), fullPage: true });
  await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
  await page.getByRole("button", { name: "Open Audience Confirmation for reader@example.test", exact: true }).click();
  await expect(page.getByRole("region", { name: "Local email message", exact: true })).toContainText("Audience Confirmation");
  const confirmationPath = await page.getByRole("link", { name: "Open newsletter action", exact: true }).getAttribute("href");
  await publicPage.goto(confirmationPath, { waitUntil: "networkidle" });
  await publicPage.getByRole("button", { name: "Confirm newsletter subscription", exact: true }).click();
  await expect(publicPage.getByRole("status")).toContainText("subscription is confirmed");
  await publicPage.screenshot({ path: testInfo.outputPath("website-newsletter-confirmation.png"), fullPage: true });
  await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
  await expect(page.getByRole("region", { name: "Newsletter audience", exact: true })).toContainText("Confirmed");
  await page.getByLabel("Newsletter subject", { exact: true }).fill("A helpful care update");
  await page.getByLabel("Newsletter text", { exact: true }).fill("# Looking after yourself\nA safe newsletter for our synthetic subscriber.");
  await page.getByRole("button", { name: "Save newsletter draft", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("draft saved");
  await page.getByRole("button", { name: "Capture unsent preview", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("No audience received");
  await expect(page.getByRole("button", { name: "Confirm local campaign", exact: true })).toBeDisabled();
  await page.getByRole("region", { name: "Newsletter campaign", exact: true }).getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm local campaign", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("queued");
  await expect(async () => {
    await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
    await expect(page.getByRole("region", { name: "Newsletter campaign", exact: true })).toContainText("Delivered · 1 captured");
  }).toPass({ timeout: 30000 });
  await page.screenshot({ path: testInfo.outputPath("website-newsletter-owner-delivery.png"), fullPage: true });
  await page.getByRole("button", { name: "Open Campaign Delivery for reader@example.test", exact: true }).click();
  const unsubscribePath = await page.getByRole("link", { name: "Unsubscribe from this newsletter", exact: true }).getAttribute("href");
  await publicPage.goto(unsubscribePath, { waitUntil: "networkidle" });
  await publicPage.getByRole("button", { name: "Unsubscribe from newsletter", exact: true }).click();
  await expect(publicPage.getByRole("status")).toContainText("No further newsletters");
  await publicPage.screenshot({ path: testInfo.outputPath("website-newsletter-unsubscribe.png"), fullPage: true });
  await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
  await expect(page.getByRole("region", { name: "Newsletter audience", exact: true })).toContainText("Unsubscribed");
  await page.getByRole("button", { name: "Suppress reader@example.test", exact: true }).click();
  await expect(page.getByRole("region", { name: "Newsletter audience", exact: true })).toContainText("Suppressed");
  await publicPage.goto(`/${marker.toLowerCase()}/blog`, { waitUntil: "networkidle" });
  const repeatedSignup = publicPage.locator('[data-newsletter-template="tena"]');
  await repeatedSignup.getByLabel("Email address", { exact: true }).fill("reader@example.test");
  await repeatedSignup.getByRole("checkbox").check();
  await repeatedSignup.getByRole("button", { name: "Receive care updates", exact: true }).click();
  await page.getByRole("button", { name: "Refresh delivery status", exact: true }).click();
  await expect(page.getByRole("region", { name: "Newsletter audience", exact: true })).toContainText("Suppressed");
  await page.screenshot({ path: testInfo.outputPath("website-newsletter-suppression-preserved.png"), fullPage: true });
  await page.goto("/settings/website/content", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Website", exact: true }).selectOption({ label: marker });
  await publicPage.setViewportSize({ width: 1440, height: 900 });
  await articleHistory(page, publicPage, testInfo, { root: `/${marker.toLowerCase()}`, title: `${marker} Preparing for your visit`, route: "/blog/preparing-for-your-visit", prefix: "website", original: "Bring your questions", draft: "A revised private guide for this consultation." });
  await guest.close();
  await page.goto("/settings/organization-import", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Organization", exact: true }).selectOption({ label: marker });
  const templateDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download workbook template", exact: true }).click();
  expect((await templateDownload).suggestedFilename()).toMatch(/\.xlsx$/);
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_BAD_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Correct these cells and upload again" })).toBeVisible();
  await expect(page.getByRole("cell", { name: "C2", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("website-workbook-correction.png"), fullPage: true });
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm import", exact: true })).toBeDisabled();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Workbook applied");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-applied.png"), fullPage: true });
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("No duplicate records");
  await page.getByRole("combobox", { name: "Organization", exact: true }).selectOption("");
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_NEW_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Workbook applied");
  await expect(page.getByRole("combobox", { name: "Organization", exact: true })).toHaveValue(marker + " Workbook");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-new-business.png"), fullPage: true });
  await page.goto("/workspaces", { waitUntil: "networkidle" });
  await page.locator('[data-qa="workspace-card"]').filter({
    has: page.getByRole("heading", { name: marker, exact: true }),
  }).getByRole("button", { name: "Open", exact: true }).click();
  await expect(page).toHaveURL(/\/home/);
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: `Resume ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "content", exact: true }).click();
  await expect(page.getByRole("group", { name: "hero", exact: true }).getByLabel("subtitle", { exact: true })).toHaveValue("Reviewed workbook website introduction.");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-draft-content.png"), fullPage: true });
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Business", exact: true }).selectOption({ label: marker + " Workbook" });
  await page.getByLabel("Website name", { exact: true }).fill(marker + " Workbook");
  await page.getByLabel("Website address", { exact: true }).fill(marker.toLowerCase() + "-workbook");
  await page.getByRole("button", { name: "Create website draft", exact: true }).click();
  await page.getByRole("button", { name: "content", exact: true }).click();
  await expect(page.getByRole("group", { name: "hero", exact: true }).getByLabel("subtitle", { exact: true })).toHaveValue("Reviewed workbook website introduction.");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-starter-content.png"), fullPage: true });
  const staffSession = await receptionist.request.get("/api/method/appointment.scheduler.membership.context");
  const staffState = (await staffSession.json()).message;
  expect(staffState.selected.role).toBe("Receptionist");
  expect(staffState.selected.location_names).toEqual([`${marker} Main`]);
  expect(staffState.workspaces).toHaveLength(1);
  await receptionist.goto("/settings/website/content", { waitUntil: "networkidle" });
  await expect(receptionist).toHaveURL(/\/reception/);
  const ownerContent = await page.request.get("/api/method/appointment.content.api.list_owned_content");
  const ownedArticle = (await ownerContent.json()).message.items.find(row => row.source_doctype === "Blog Post" && row.title === `${marker} Preparing for your visit`);
  expect(ownedArticle).toBeTruthy();
  const denied = await receptionist.request.post("/api/method/appointment.content.api.publish_article", { data: { ownership: ownedArticle.name } });
  expect(denied.status()).toBe(403);
  const deniedBody = await denied.json();
  expect(deniedBody.exc_type).toBe("PermissionError");
  expect(JSON.stringify(deniedBody)).not.toContain(`${marker} Preparing for your visit`);
  await receptionist.screenshot({ path: testInfo.outputPath("website-receptionist-publishing-denied.png"), fullPage: true });
  writeFileSync(testInfo.outputPath("website-staff-validation.json"), JSON.stringify({
    managed_browser_account: profile.browser_account, managed_browser_session: profile.browser_session,
    roles: profile.roles, user: profile.user, scope: staffState.selected.location_names,
    cross_business_workspace_count: staffState.workspaces.length, publication_denied: true,
    account_created_by: "Guest invitation acceptance", role_assigned_by: "Normal owner Team UI",
  }, null, 2));

  await businessIsolation(page, receptionist, testInfo, marker);
});
