import { test, expect } from "playwright/test";

test("website-owner-journey", async ({ page }, testInfo) => {
  page.setDefaultTimeout(20000);
  page.setDefaultNavigationTimeout(30000);
  const marker = process.env.WEBSITE_QA_MARKER;
  expect(marker).toMatch(/^WQA-[a-zA-Z0-9]+$/);
  const identity = await page.request.get("/api/method/frappe.auth.get_logged_user");
  expect((await identity.json()).message).toBe("content-browser-owner@example.test");
  await page.goto("/onboarding", { waitUntil: "networkidle" });
  await page.getByLabel("Business name", { exact: true }).fill(marker);
  await page.getByLabel("Location name", { exact: true }).fill(`${marker} Main`);
  await page.getByLabel("First service name", { exact: true }).fill(`${marker} Consultation`);
  await page.getByRole("button", { name: "Create business", exact: true }).click();
  await expect(page).toHaveURL(/\/home/);
  await page.goto("/settings/business", { waitUntil: "networkidle" });
  await page.locator('[data-qa="business-offering"]').filter({ hasText: marker }).getByRole("button", { name: "Publish booking page", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await expect(page.getByRole("heading", { name: "Website setup", exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Business", exact: true }).selectOption({ label: marker });
  await page.getByRole("combobox", { name: "Business focus", exact: true }).selectOption("health");
  await page.getByRole("combobox", { name: "Feeling", exact: true }).selectOption("calm");
  await page.getByLabel("Website name", { exact: true }).fill(marker);
  await page.getByLabel("Website address", { exact: true }).fill(marker.toLowerCase());
  await page.getByRole("button", { name: "Create website draft", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "content", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("saved");
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("button", { name: `Resume ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "Save and return later", exact: true }).click();
  await expect(page).toHaveURL(/\/home/);
  await page.goto("/settings/website", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: `Resume ${marker}`, exact: true }).click();
  await page.getByRole("button", { name: "features", exact: true }).click();
  await page.getByLabel("blog", { exact: true }).check();
  await page.getByLabel("gallery", { exact: true }).check();
  await page.getByRole("button", { name: "readiness", exact: true }).click();
  await page.getByRole("button", { name: "Check readiness", exact: true }).click();
  await expect(page.getByText("Ready: website draft", { exact: true })).toBeVisible();
  await expect(page.getByText("Ready: booking", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Live preview of saved draft", exact: true }).click();
  await expect(page.getByRole("region", { name: "Website live preview" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("website-preview-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Publish website", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await page.screenshot({ path: testInfo.outputPath("website-published-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath("website-published-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/settings/website/content", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Website", exact: true }).selectOption({ label: marker });
  await page.getByLabel("Article title", { exact: true }).fill(`${marker} Preparing for your visit`);
  await page.getByLabel("Article address", { exact: true }).fill("preparing-for-your-visit");
  await page.getByLabel("Summary", { exact: true }).fill("A guide to preparing for your consultation.");
  await page.getByLabel("Article text", { exact: true }).fill("# Preparing for your visit\nBring your questions and allow time to arrive.");
  await page.getByRole("button", { name: "Save article draft", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("draft saved");
  await page.getByRole("button", { name: "Publish article", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("published");
  await page.screenshot({ path: testInfo.outputPath("website-article-workspace.png"), fullPage: true, mask: [page.locator("time")] });
  const galleryEditor = page.getByRole("region", { name: "Gallery editor" });
  await galleryEditor.getByLabel("Collection title", { exact: true }).fill("Around our clinic");
  await galleryEditor.getByLabel("Collection address", { exact: true }).fill("around-our-clinic");
  await galleryEditor.getByLabel("Gallery image", { exact: true }).setInputFiles(process.env.WEBSITE_QA_IMAGE);
  await galleryEditor.getByLabel("Image description", { exact: true }).fill("A consultation at the clinic");
  await galleryEditor.getByLabel("Caption", { exact: true }).fill("A welcoming place to talk about your health.");
  await galleryEditor.getByRole("checkbox").check();
  await galleryEditor.getByRole("button", { name: "Save gallery draft", exact: true }).click();
  await expect(galleryEditor.getByRole("status")).toContainText("draft saved");
  await galleryEditor.getByRole("button", { name: "Publish gallery", exact: true }).click();
  await expect(galleryEditor.getByRole("status")).toContainText("published");
  // Public reads use a separate guest context, without the owner login cookies.
  const guest = await page.context().browser().newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL });
  const publicPage = await guest.newPage();
  publicPage.setDefaultTimeout(20000);
  publicPage.setDefaultNavigationTimeout(30000);
  await publicPage.goto(`/${marker.toLowerCase()}`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.locator("h1")).toContainText(marker);
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-landing.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/book`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.locator("h1")).toContainText(marker);
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-book.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/blog`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.locator("main")).toContainText("Preparing for your visit");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-blog.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/blog/preparing-for-your-visit`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.locator("main")).toContainText("Bring your questions");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-article.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/gallery`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.locator("main")).toContainText("Around our clinic");
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-gallery.png"), fullPage: true });
  await publicPage.goto(`/${marker.toLowerCase()}/gallery/around-our-clinic`, { waitUntil: "domcontentloaded" });
  await expect(publicPage.getByRole("img", { name: "A consultation at the clinic", exact: true })).toBeVisible();
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-collection-desktop.png"), fullPage: true });
  await publicPage.setViewportSize({ width: 390, height: 844 });
  await publicPage.getByRole("button", { name: "Switch to dark mode", exact: true }).click();
  await expect(publicPage.locator('[data-pe-mode="dark"]')).toBeVisible();
  await publicPage.screenshot({ path: testInfo.outputPath("website-guest-collection-mobile-dark.png"), fullPage: true });
  await guest.close();
  await page.goto("/settings/organization-import", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Organization", exact: true }).selectOption({ label: marker });
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_BAD_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Correct these cells and upload again" })).toBeVisible();
  await expect(page.getByRole("cell", { name: "C2", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("website-workbook-correction.png"), fullPage: true });
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm import", exact: true })).toBeDisabled();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Workbook applied");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-applied.png"), fullPage: true });
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("No duplicate records");
  await page.getByRole("combobox", { name: "Organization", exact: true }).selectOption("");
  await page.getByLabel("Organization workbook", { exact: true }).setInputFiles(process.env.WEBSITE_QA_NEW_WORKBOOK);
  await page.getByRole("button", { name: "Review workbook", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ready for confirmation" })).toBeVisible();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Confirm import", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Workbook applied");
  await expect(page.getByRole("combobox", { name: "Organization", exact: true })).toHaveValue(marker + " Workbook");
  await page.screenshot({ path: testInfo.outputPath("website-workbook-new-business.png"), fullPage: true });
});
